Corrected error in lint checks
kofimeighan/adelardos-capstone-2020 pull request #8
Opened 2020-06-29 19:48 UTC by Jaxobc

2020-06-29 19:49 UTC, kennzoid approved these changes

2020-06-29 19:57 UTC, wangtong-g requested changes
I believe this intends to fix the lint error in previous PR #7. Then it should be part of it instead of a new one.

2020-06-29 21:12 UTC, Jaxobc commented
> I believe this intends to fix the lint error in previous PR #7. Then it should be part of it instead of a new one.

Kenneth stated that I could add to my previous PR or make a new one and I chose to make a new one because I would like the lint check to pass before I merge the changes to master. If I include it in my previous PR, I will not know whether this corrects the error or not.

2020-06-30 03:13 UTC, wangtong-g approved these changes
Oh, I see. Sounds good.

2020-06-30 14:16 UTC, merged